Add initial build, test, and scan jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,7 +43,14 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
+            cd frontend
+            npm i
+            npm run build
+      - run:
+          name: Handle front-end build failure
+          when: on_fail
+          command: |
+            echo "Front end failed to build"
             exit 1
       - save_cache:
           paths: [frontend/node_modules]
@@ -59,40 +66,103 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            cd backend
+            npm i
+            npm run build
+      - run:
+          name: Handle back-end build failure
+          when: on_fail
+          command: |
+            echo "Back-end failed to build"
+            exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
+      - checkout
+      - restore_cache:
+          keys: [ frontend-build ]
+      - run:
+          name: Test frontend
+          command: |
+            cd frontend
+            npm run test
+      - run:
+          name: Handle frontend test failure
+          when: on_fail
+          command: |
+            echo "Frontend tests failed"
+            exit 1
       # Checkout code from git
       # Restore from cache
       # Your job code here
                 
   test-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
+      - checkout
+      - restore_cache:
+          keys: [ backend-build ]
+      - run:
+          name: Test backend
+          command: |
+            cd backend
+            npm run test
+      - run:
+          name: Handle back-end test failure
+          when: on_fail
+          command: |
+            echo "Backend tests failed"
+            exit 1
       # Checkout code from git
       # Restore from cache
       # Your job code here
             
   scan-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
+      - checkout
+      - restore_cache:
+          keys: [ frontend-build ]
+      - run:
+          name: Scan frontend
+          command: |
+            cd frontend
+            npm audit --audit-level=critical
+      - run:
+          name: Handle frontend scan failure
+          when: on_fail
+          command: |
+            echo "Frontend scan failed"
+            exit 1
       # Checkout code from git
       # Restore from cache
       # Your job code here
 
   scan-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
+      - checkout
+      - restore_cache:
+          keys: [ backend-build ]
+      - run:
+          name: Scan backend
+          command: |
+            cd backend
+            npm audit --audit-level=critical
+      - run:
+          name: Handle back-end scan failure
+          when: on_fail
+          command: |
+            echo "Backend scan failed"
+            exit 1
       # Checkout code from git
       # Restore from cache
       # Your job code here
@@ -243,7 +313,7 @@ jobs:
             # your code here
       # Here's where you will add some code to rollback on failure  
 
-cleanup:
+  cleanup:
     docker:
       # Docker image here
     steps:
@@ -276,22 +346,22 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [test-feature-branch]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+#      - deploy-infrastructure:
+#          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+#          filters:
+#            branches:
+#              only: [test-feature-branch]
+#      - configure-infrastructure:
+#          requires: [deploy-infrastructure]
+#      - run-migrations:
+#          requires: [configure-infrastructure]
+#      - deploy-frontend:
+#          requires: [run-migrations]
+#      - deploy-backend:
+#          requires: [run-migrations]
+#      - smoke-test:
+#          requires: [deploy-backend, deploy-frontend]
+#      - cloudfront-update:
+#          requires: [smoke-test]
+#      - cleanup:
+#          requires: [cloudfront-update]
